### ISSUE TITLE
Debug messages

### ISSUE THREAD

**Issue by dotellie** [LostInBrittany/granite-file-reader#3]
I don't know why all debug messages are left in the code, but it's quite annoying to see them every time you interact with the element. What's the reason for them being there and is it possible to have them removed?

**Comment by LostInBrittany** [comment]
There was no true reason to have all the debug messages in code, besides that I used the elements in some projects with my students and it seemed clearer to have the messages... I have put them besides a `debug` attribute, so you get o messages by default.

**Comment by dotellie** [comment]
Awesome! Thanks for the quick response! 😄
